### ISSUE TITLE
Python3 compatible version

### ISSUE THREAD

**Issue by slavkoja** [gilesbrown/gsqlite3#5]
Please, release Python3 compatible version. I tried id today with Python 3.6 and after installing git version, demo.py works:
```
python demo.py 
Populating 'demo.sqlite' ...
raw times: 0.988 0.902 0.954
gsqlite3: 10 loops,
best of 3: 90.2 msec per loop
raw times: 2.11 2.12 2.13
sqlite3: 10 loops,
best of 3: 211 msec per loop
```
But hte latest PyPi  version (0.1.3) fails with #2

**Comment by LefterisJP** [comment]
+1 

Can you please make a new release of the package?

**Comment by gilesbrown** [comment]
Oh my goodness. Never knew anyone was using this. Should be easy enough but if you want to create a PR that would be great.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gilesbrown** [comment]
I just ran it under Python3 and it works for me. 🤷
