### ISSUE TITLE
sharing connection between threads

### ISSUE THREAD

**Issue by fried-sausage** [gilesbrown/gsqlite3#7]
As i understand, we create connection in one thread and then execute query (reusing same connection) in another thread. From what i've read this is not safe when using sqlite3 library.

https://docs.python.org/3/library/sqlite3.html#sqlite3.connect
> When using multiple threads with the same connection writing operations should be serialized by the user to avoid data corruption.

https://stackoverflow.com/a/22739924
> It's not safe to share a connection between threads; at the very least you need to use a lock to serialize access

**Comment by gilesbrown** [comment]
We would only use the same connection in multiple threads if we use the same connection in multiple greenlets because the threadpool usage is constrained with the call structure of the greenlet invoking the method on the Cursor.

I suppose I could add a check for that.
